#!/bin/bash
set -e

cd server/app
echo "Formatting Go files..."
goimports -w .
echo "Running Go lint..."
golangci-lint run
cd ../../

cd client/web
echo "Formatting JS/TS files..."
pnpm format
echo "Running JS/TS lint..."
pnpm lint
cd ../../
