name: Server CI

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/build-server.yml'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    name: Lint & Format Server
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.5.0

      - name: Format code
        run: |
          cd server/app
          goimports -w .

      - name: Lint code
        run: |
          cd server/app
          golangci-lint run .


  build-and-push:
    runs-on: ubuntu-latest
    name: Build & Push Server Docker Image
    needs: lint-and-format
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set environment variables
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          REPO_NAME=$(echo "${GITHUB_REPOSITORY#*/}" | awk '{print tolower($0)}')
          SERVER_IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/${REPO_NAME}-server:${BRANCH_NAME}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "SERVER_IMAGE_TAG=$SERVER_IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ env.SERVER_IMAGE_TAG }} ./server

      - name: Push Docker image
        run: docker push ${{ env.SERVER_IMAGE_TAG }}
