name: Build & Push Server Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/build-server.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build & Push Server Docker Image
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set environment variables
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          REPO_NAME=$(echo "${GITHUB_REPOSITORY#*/}" | awk '{print tolower($0)}')
          SERVER_IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/${REPO_NAME}-server:${BRANCH_NAME}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "SERVER_IMAGE_TAG=$SERVER_IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ env.SERVER_IMAGE_TAG }} ./server

      - name: Push Docker image
        run: docker push ${{ env.SERVER_IMAGE_TAG }}
