name: Build and Push Client Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/build-client.yml'

jobs:
  build-and-push-client:
    runs-on: ubuntu-latest
    name: Build and Push Client Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get current branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get repository name
        run: echo "REPO_NAME=$(echo \"${GITHUB_REPOSITORY#*/}\" | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: Set image tag
        run: echo "CLIENT_IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}-client:${{ env.BRANCH_NAME }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ env.CLIENT_IMAGE_TAG }} ./client

      - name: Push Docker image
        run: docker push ${{ env.CLIENT_IMAGE_TAG }}
