name: Build and Push Server Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/build-server.yml'

jobs:
  build-and-push-server:
    runs-on: ubuntu-latest
    name: Build and Push Server Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get current branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get repository name
        run: echo "REPO_NAME=$(echo \"${GITHUB_REPOSITORY#*/}\" | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: Set image tag
        run: echo "SERVER_IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}-server:${{ env.BRANCH_NAME }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ env.SERVER_IMAGE_TAG }} ./server

      - name: Push Docker image
        run: docker push ${{ env.SERVER_IMAGE_TAG }}
